/*
 * Copyright 2012 - 2025 Manuel Laggner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.tinymediamanager.scraper.util;

import java.util.Locale;

/**
 * Alternative string similarity using the Jaro-Winkler algorithm, generated by Github Copilot
 */
public final class AdvancedSimilarity {
  private AdvancedSimilarity() {
  }

  public static float compareStrings(String s1, String s2) {
    if (s1 == null || s2 == null) {
      return 0.0f;
    }
    String a = normalize(s1);
    String b = normalize(s2);
    if (a.equalsIgnoreCase(b)) {
      return 1.0f;
    }
    double jw = jaroWinkler(a, b);
    if (Double.isNaN(jw) || jw < 0.0) {
      return 0.0f;
    }
    return (float) jw;
  }

  private static String normalize(String s) {
    if (s == null) {
      return "";
    }
    // trim, collapse whitespace, uppercase for case-insensitive comparison
    return s.trim().replaceAll("\\s+", " ").toUpperCase(Locale.ROOT);
  }

  private static double jaroWinkler(String s1, String s2) {
    double jaro = jaroDistance(s1, s2);
    // standard Winkler boost parameters
    final double scalingFactor = 0.1;
    // compute common prefix up to 4 chars
    int prefix = 0;
    int maxPrefix = 4;
    int lim = Math.min(Math.min(s1.length(), s2.length()), maxPrefix);
    for (int i = 0; i < lim; i++) {
      if (s1.charAt(i) == s2.charAt(i)) {
        prefix++;
      }
      else {
        break;
      }
    }
    return jaro + prefix * scalingFactor * (1.0 - jaro);
  }

  private static double jaroDistance(String s1, String s2) {
    if (s1.isEmpty() && s2.isEmpty()) {
      return 1.0;
    }
    if (s1.isEmpty() || s2.isEmpty()) {
      return 0.0;
    }
    int len1 = s1.length();
    int len2 = s2.length();
    int matchDistance = Math.max(len1, len2) / 2 - 1;
    if (matchDistance < 0) {
      matchDistance = 0;
    }

    boolean[] s1Matches = new boolean[len1];
    boolean[] s2Matches = new boolean[len2];
    int matches = 0;

    for (int i = 0; i < len1; i++) {
      int start = Math.max(0, i - matchDistance);
      int end = Math.min(len2 - 1, i + matchDistance);
      for (int j = start; j <= end; j++) {
        if (!s2Matches[j] && s1.charAt(i) == s2.charAt(j)) {
          s1Matches[i] = true;
          s2Matches[j] = true;
          matches++;
          break;
        }
      }
    }

    if (matches == 0) {
      return 0.0;
    }

    int t = 0;
    int k = 0;
    for (int i = 0; i < len1; i++) {
      if (!s1Matches[i])
        continue;
      while (!s2Matches[k]) {
        k++;
      }
      if (s1.charAt(i) != s2.charAt(k)) {
        t++;
      }
      k++;
    }
    double transpositions = t / 2.0;

    return ((matches / (double) len1) + (matches / (double) len2) + ((matches - transpositions) / matches)) / 3.0;
  }
}
